=== zinwei0906/Practical_PHP_Programming/Degree/Practical(IP)/P4Q1/Catalog.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT catalog (book)*>
<!ELEMENT book (title, author*, publisher,bookISBN)*>

<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT bookISBN (bookISBN10|bookISBN13)>
<!ELEMENT bookISBN10 (#PCDATA)>
<!ELEMENT bookISBN13 (#PCDATA)>

<!ATTLIST __ROOT__ version CDATA #REQUIRED>

=== zinwei0906/Practical_PHP_Programming/Degree/Practical(IP)/P4Q5/Catalog.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--<!DOCTYPE catalog SYSTEM "Catalog.dtd">-->
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="Catelog.xsd">
<!--<catalog>-->
    <book>
        <title>Hello World</title>
        <author>Java</author>
        <author>Java 2</author>
        <publisher>Java Publisher</publisher>
        <bookISBN>
            <bookISBN10>8910101010</bookISBN10> 
        </bookISBN>
    </book>
    <book>
        <title>Good Bye</title>
        <author>C++</author>
        <publisher>C++ Publisher</publisher>
        <bookISBN>
            <bookISBN13>978-1234567890</bookISBN13> 
        </bookISBN>
    </book>
</catalog>

=== zinwei0906/Practical_PHP_Programming/Degree/Practical(IP)/P4Q1/Catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->


<!DOCTYPE catalog SYSTEM "Catalog.dtd">
<catalog>
    <book>
        <title>Hello World</title>
        <author>Java</author>
        <author>Java 2</author>
        <publisher>Java Publisher</publisher>
        <bookISBN>
            <bookISBN10>8910101010</bookISBN10> 
        </bookISBN>
    </book>
    <book>
        <title>Good Bye</title>
        <author>C++</author>
        <publisher>C++ Publisher</publisher>
        <bookISBN>
            <bookISBN13>978-1234567890</bookISBN13> 
        </bookISBN>
    </book>
</catalog>
